# This section includes...
1. Matrice creation
2. Creation of matrices with default initionalisation values
    - Zeros
    - Ones
3. Initialize seeds for reproducibility on GPU and CPU
4. Convert Matrices: NumPy => Torch && Torch => NumPy
5. Moving Tensors from GPU => CPU && CPU => GPU
6. Run important Tensor operations:
    - Element-wise(Addition, Subtraction, multiplication and division)
    - Resizing
    - Calulate(mean and standard deviation)

In [147]:
import numpy as np

In [11]:
arr = [[1, 2],[3, 4]]; print arr

[[1, 2], [3, 4]]


In [12]:
new_arr = np.array(arr); print(new_arr)

[[1 2]
 [3 4]]


In [13]:
import torch

In [20]:
torch.Tensor(new_arr)


 1  2
 3  4
[torch.FloatTensor of size 2x2]

In [21]:
ones = np.ones((2, 2)); print ones

[[ 1.  1.]
 [ 1.  1.]]


In [26]:
torch.ones((2, 2))


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [28]:
np.random.rand(2, 2)

array([[ 0.96838487,  0.16625789],
       [ 0.52010032,  0.86561743]])

In [30]:
torch.rand(2, 2)


 0.4015  0.3709
 0.8267  0.2010
[torch.FloatTensor of size 2x2]

### Seeds for reproducibility

In [2]:
# np seed
np.random.seed(0)
np.random.rand(2, 2)

array([[ 0.5488135 ,  0.71518937],
       [ 0.60276338,  0.54488318]])

In [3]:
np.random.rand(2, 2)

array([[ 0.4236548 ,  0.64589411],
       [ 0.43758721,  0.891773  ]])

In [4]:
np.random.seed(0)
np.random.rand(2, 2)

array([[ 0.5488135 ,  0.71518937],
       [ 0.60276338,  0.54488318]])

In [7]:
# Torch seed
torch.manual_seed(0)
torch.rand(2, 2)


 0.5488  0.5928
 0.7152  0.8443
[torch.FloatTensor of size 2x2]

In [8]:
torch.manual_seed(0)
torch.rand(2, 2)


 0.5488  0.5928
 0.7152  0.8443
[torch.FloatTensor of size 2x2]

In [11]:
if torch.cuda.is_available():
    print("Yes")
else:
    print("No!")

No!


### Numpy to torch bridge

In [16]:
np_array = np.ones((2, 2)); print np_array

[[ 1.  1.]
 [ 1.  1.]]


In [17]:
print type(np_array)

<type 'numpy.ndarray'>


In [18]:
our_torch_tensor = torch.from_numpy(np_array); print our_torch_tensor


 1  1
 1  1
[torch.DoubleTensor of size 2x2]



In [19]:
print type(our_torch_tensor)

<class 'torch.DoubleTensor'>


In [20]:
# Datatypes matter: intentional error
np_array_new = np.ones((2, 2), dtype=np.int8)

In [21]:
torch.from_numpy(np_array_new)

RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.

In [22]:
''' 
    Torch can only convert: double, float, int64, int32, and uint8.
    
    to torch Tensors.
'''

' \n    Torch can only convert: double, float, int64, int32, and uint8.\n    \n    to torch Tensors.\n'

In [24]:
np_array_new = np.ones((2, 2), dtype=np.int64)

In [26]:
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.LongTensor of size 2x2]

In [27]:
# It works now!!

### Summary

When I see error messages that refer to these particular tensor types, refer to this guide.

|NumPy Array Type|Torch Tensor Type|  
|             ---|              ---|
|int64|LongTensor|
|int32|IntegerTensor|  
|uint8|ByteTensor|  
|float64|DoubleTensor|  
|float32|FloatTensor| 
|double|DoubleTensor|  

## Torch to NumPy

In [31]:
torch_tensor = torch.ones(2, 2); print torch_tensor


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [33]:
type(torch_tensor)

torch.FloatTensor

In [36]:
torch_to_numpy = torch_tensor.numpy(); print torch_to_numpy

[[ 1.  1.]
 [ 1.  1.]]


In [38]:
type(torch_to_numpy)

numpy.ndarray

### Tensors CPU -> GPU Conversion and back

In [39]:
# Tensors are CPU made by default
tensor_cpu = torch.ones(2, 2)

In [41]:
# CPU to GPU
if torch.cuda.is_available():
    tensor_gpu = tensor_cpu.cuda

In [43]:
# GPU to CPU
tensor_cpu = tensor_gpu.cpu() # This won't work on computers with no GPU


 1  1
 1  1
[torch.FloatTensor of size 2x2]

### Tensor operations

### Resizing Tensor

In [44]:
a = torch.ones(2, 2)

In [45]:
print a


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [46]:
print a.size()

torch.Size([2, 2])


In [47]:
a.view(4)


 1
 1
 1
 1
[torch.FloatTensor of size 4]

In [51]:
a.view(4).size()

torch.Size([4])

In [52]:
z = a.view(4)

In [53]:
z


 1
 1
 1
 1
[torch.FloatTensor of size 4]

### Element-wise addition

In [54]:
a = torch.ones(2, 2); print a


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [55]:
b = torch.ones(2, 2); print b


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [57]:
c = a + b; print c
# same as saying...
c = torch.add(a, b)


 2  2
 2  2
[torch.FloatTensor of size 2x2]



In [58]:
print("Old c tensor")
print c

Old c tensor

 2  2
 2  2
[torch.FloatTensor of size 2x2]



In [59]:
# In place addition
c.add_(a)   # var.operation_(argument) is an in place operation
print "New C tentor"
print c

New C tentor

 3  3
 3  3
[torch.FloatTensor of size 2x2]



### Element wise subtraction

In [105]:
a = torch.ones(2, 2); print a


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [106]:
b = torch.ones(2, 2); print b


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [107]:
a - b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [108]:
print a.sub_(b)

# Where... a.sub_(b) would replace a with a - b


 0  0
 0  0
[torch.FloatTensor of size 2x2]



In [109]:
print a


 0  0
 0  0
[torch.FloatTensor of size 2x2]



### Element-wise multiplication

In [110]:
a = torch.ones(2, 2)
print a
b = torch.zeros(2, 2)
print b


 1  1
 1  1
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



In [111]:
a * b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [112]:
print torch.mul(a, b)
print a


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [113]:
print a.mul_(b) # Same as saying a = a * b
print a


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



### Element-wise division

In [114]:
a = torch.ones(2, 2)
print a
b = torch.zeros(2, 2)
print b


 1  1
 1  1
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



In [115]:
torch.div(b, a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [116]:
b.div_(a)
print b


 0  0
 0  0
[torch.FloatTensor of size 2x2]



### Tensor mean

- 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 = 55
- mean = 55/10 = 5.5

In [118]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.size()

torch.Size([10])

In [131]:
a.mean(dim=0) # Dim = 0 means there's only one dimension


 5.5000
[torch.FloatTensor of size 1]

In [132]:
a.mean(dim=1) # Doesn't work because there's no columns or anything to var a

RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

In [136]:
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]); print a


    1     2     3     4     5     6     7     8     9    10
    1     2     3     4     5     6     7     8     9    10
[torch.FloatTensor of size 2x10]



In [137]:
a.size()

torch.Size([2, 10])

In [138]:
a.mean(dim=0)


  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
[torch.FloatTensor of size 10]

In [140]:
a.mean(dim=1)


 5.5000
 5.5000
[torch.FloatTensor of size 2]

### Tensor standard deviation

In [141]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [146]:
a.std(dim=0)


 3.0277
[torch.FloatTensor of size 1]